/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package osm.views;

/**
 *
 * @author Omar
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
               
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jbtnTBAddOffer = new javax.swing.JButton();
        jbtnTBAddItem = new javax.swing.JButton();
        jbtnTBAddClient = new javax.swing.JButton();
        jbtnTBAddBank = new javax.swing.JButton();
        jpnlSearch = new javax.swing.JPanel();
        jtpSearch = new javax.swing.JTabbedPane();
        jpnlSearchOffers = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfSearchRefNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbxSearchDate = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jcmxSearchClientID = new javax.swing.JComboBox();
        jcbxSearchClientID = new javax.swing.JCheckBox();
        jftfSearchFromDate = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jftfSearchToDate = new javax.swing.JFormattedTextField();
        jcbxSearchRefNo = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jcmxSearchProject = new javax.swing.JComboBox();
        jcbxSearchProject = new javax.swing.JCheckBox();
        jbtnOfferSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jcmxSearchItemID = new javax.swing.JComboBox();
        jbtnItemSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblSearchResult = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jbtnPrevGroup = new javax.swing.JButton();
        jbtnPrev = new javax.swing.JButton();
        jlblPaging = new javax.swing.JLabel();
        jbtnNext = new javax.swing.JButton();
        jbtnNextGroup = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbtnEdit = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jbtnTBAddOffer.setText("Add Offer");
        jbtnTBAddOffer.setFocusable(false);
        jbtnTBAddOffer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnTBAddOffer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnTBAddOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTBAddOfferActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnTBAddOffer);

        jbtnTBAddItem.setText("Add Item");
        jbtnTBAddItem.setFocusable(false);
        jbtnTBAddItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnTBAddItem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnTBAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTBAddItemActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnTBAddItem);

        jbtnTBAddClient.setText("Add Client");
        jbtnTBAddClient.setFocusable(false);
        jbtnTBAddClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnTBAddClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnTBAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTBAddClientActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnTBAddClient);

        jbtnTBAddBank.setText("Add Bank");
        jbtnTBAddBank.setFocusable(false);
        jbtnTBAddBank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnTBAddBank.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnTBAddBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTBAddBankActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnTBAddBank);

        jpnlSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jpnlSearchOffers.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Conditions"));
        jpnlSearchOffers.setToolTipText("NGC/Services xxx-2015");

        jLabel1.setText("Reference No.:");

        jtfSearchRefNo.setToolTipText("example: NGC/Services xxx-2015");

        jLabel2.setText("Date:");

        jLabel3.setText("Client ID:");

        jcmxSearchClientID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("To:");

        jLabel6.setText("Project");

        jcmxSearchProject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbxSearchProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxSearchProjectActionPerformed(evt);
            }
        });

        jbtnOfferSearch.setText("Search");

        javax.swing.GroupLayout jpnlSearchOffersLayout = new javax.swing.GroupLayout(jpnlSearchOffers);
        jpnlSearchOffers.setLayout(jpnlSearchOffersLayout);
        jpnlSearchOffersLayout.setHorizontalGroup(
            jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSearchOffersLayout.createSequentialGroup()
                .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnOfferSearch)
                    .addGroup(jpnlSearchOffersLayout.createSequentialGroup()
                        .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlSearchOffersLayout.createSequentialGroup()
                                .addComponent(jtfSearchRefNo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbxSearchRefNo)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(jpnlSearchOffersLayout.createSequentialGroup()
                                .addComponent(jftfSearchFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftfSearchToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbxSearchDate)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7)))
                        .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcmxSearchClientID, 0, 240, Short.MAX_VALUE)
                            .addComponent(jcmxSearchProject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbxSearchClientID)
                    .addComponent(jcbxSearchProject))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlSearchOffersLayout.setVerticalGroup(
            jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSearchOffersLayout.createSequentialGroup()
                .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbxSearchRefNo)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtfSearchRefNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcmxSearchProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbxSearchProject)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlSearchOffersLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcmxSearchClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(jpnlSearchOffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jftfSearchFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jftfSearchToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbxSearchClientID, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jcbxSearchDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnOfferSearch))
        );

        jtpSearch.addTab("Offers", jpnlSearchOffers);
        jpnlSearchOffers.getAccessibleContext().setAccessibleDescription("example: NGC/Services xxx-2015");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Conditions"));

        jLabel7.setText("Item ID:");

        jcmxSearchItemID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnItemSearch.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcmxSearchItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 474, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnItemSearch)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcmxSearchItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jbtnItemSearch))
        );

        jtpSearch.addTab("Items", jPanel1);

        javax.swing.GroupLayout jpnlSearchLayout = new javax.swing.GroupLayout(jpnlSearch);
        jpnlSearch.setLayout(jpnlSearchLayout);
        jpnlSearchLayout.setHorizontalGroup(
            jpnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpnlSearchLayout.setVerticalGroup(
            jpnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSearchLayout.createSequentialGroup()
                .addComponent(jtpSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtblSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblSearchResult);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToolBar2.setRollover(true);

        jbtnPrevGroup.setText("<<");
        jbtnPrevGroup.setFocusable(false);
        jbtnPrevGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPrevGroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbtnPrevGroup);

        jbtnPrev.setText("<");
        jbtnPrev.setFocusable(false);
        jbtnPrev.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPrev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbtnPrev);

        jlblPaging.setText("xx of Total");
        jToolBar2.add(jlblPaging);

        jbtnNext.setText(">");
        jbtnNext.setFocusable(false);
        jbtnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbtnNext);

        jbtnNextGroup.setText(">>");
        jbtnNextGroup.setFocusable(false);
        jbtnNextGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNextGroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnNextGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextGroupActionPerformed(evt);
            }
        });
        jToolBar2.add(jbtnNextGroup);
        jToolBar2.add(jSeparator1);

        jbtnEdit.setText("Edit");
        jbtnEdit.setFocusable(false);
        jbtnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbtnEdit);

        jbtnRemove.setText("Remove");
        jbtnRemove.setFocusable(false);
        jbtnRemove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbtnRemove);

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Omar\\Pictures\\07ec19f (1).png")); // NOI18N
        jLabel9.setText("National Group Co.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxSearchProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxSearchProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxSearchProjectActionPerformed

    private void jbtnNextGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnNextGroupActionPerformed

    private void jbtnTBAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTBAddItemActionPerformed
        // TODO add your handling code here:
        AddItem addItemForm=new AddItem();
        addItemForm.setVisible(true);
    }//GEN-LAST:event_jbtnTBAddItemActionPerformed

    private void jbtnTBAddOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTBAddOfferActionPerformed
        // TODO add your handling code here:
        AddOffer addOfferForm=new AddOffer();
        addOfferForm.setVisible(true);
        
    }//GEN-LAST:event_jbtnTBAddOfferActionPerformed

    private void jbtnTBAddBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTBAddBankActionPerformed
        // TODO add your handling code here:
        AddBank addBankForm=new AddBank();
        addBankForm.setVisible(true);
    }//GEN-LAST:event_jbtnTBAddBankActionPerformed

    private void jbtnTBAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTBAddClientActionPerformed
        // TODO add your handling code here:
        AddClient addClientForm=new AddClient();
        addClientForm.setVisible(true);
    }//GEN-LAST:event_jbtnTBAddClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnItemSearch;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton jbtnNextGroup;
    private javax.swing.JButton jbtnOfferSearch;
    private javax.swing.JButton jbtnPrev;
    private javax.swing.JButton jbtnPrevGroup;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnTBAddBank;
    private javax.swing.JButton jbtnTBAddClient;
    private javax.swing.JButton jbtnTBAddItem;
    private javax.swing.JButton jbtnTBAddOffer;
    private javax.swing.JCheckBox jcbxSearchClientID;
    private javax.swing.JCheckBox jcbxSearchDate;
    private javax.swing.JCheckBox jcbxSearchProject;
    private javax.swing.JCheckBox jcbxSearchRefNo;
    private javax.swing.JComboBox jcmxSearchClientID;
    private javax.swing.JComboBox jcmxSearchItemID;
    private javax.swing.JComboBox jcmxSearchProject;
    private javax.swing.JFormattedTextField jftfSearchFromDate;
    private javax.swing.JFormattedTextField jftfSearchToDate;
    private javax.swing.JLabel jlblPaging;
    private javax.swing.JPanel jpnlSearch;
    private javax.swing.JPanel jpnlSearchOffers;
    private javax.swing.JTable jtblSearchResult;
    private javax.swing.JTextField jtfSearchRefNo;
    private javax.swing.JTabbedPane jtpSearch;
    // End of variables declaration//GEN-END:variables
}
